In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.3'

In [4]:
n=np.random.randint(22,33,(5,2));print(n)

[[32 32]
 [29 25]
 [23 28]
 [28 29]
 [25 28]]

In [5]:
np.sort(n,axis=1)

array([[32, 32],
       [25, 29],
       [23, 28],
       [28, 29],
       [25, 28]])

In [6]:
np.sort(n,axis=None)

array([23, 25, 25, 28, 28, 28, 29, 29, 32, 32])

In [7]:
np.sort(n,axis=0)

array([[23, 25],
       [25, 28],
       [28, 28],
       [29, 29],
       [32, 32]])

In [8]:
np.argsort(n,axis=0)

array([[2, 1],
       [4, 2],
       [3, 4],
       [1, 3],
       [0, 0]])

In [9]:
x=np.array([3,1,2])
np.argsort(x)

array([1, 2, 0])

In [10]:
x=np.array([3,1,2])
np.argsort(x,axis=-1)

array([1, 2, 0])

In [11]:
x=np.array([3,1,2])
np.argsort(-x)

array([0, 2, 1])

In [12]:
sub=np.array(["c","c++","ds","java","ai"])
skill=np.array(["algorithm","logic","python","js","llm"])
sa=np.lexsort((sub,skill))
print(sa)
list(zip(sub[sa],skill[sa]))

[0 3 4 1 2]

[(np.str_('c'), np.str_('algorithm')),
 (np.str_('java'), np.str_('js')),
 (np.str_('ai'), np.str_('llm')),
 (np.str_('c++'), np.str_('logic')),
 (np.str_('ds'), np.str_('python'))]

In [13]:
import pandas as pd

In [14]:
m=pd.Series(["a","b","c","d"])
print(m)
print(type(m))

0    a
1    b
2    c
3    d
dtype: object
<class 'pandas.core.series.Series'>

In [15]:
a=np.array(["a","b","a","a","s","g"])
b=pd.Series(a,index=[201,202,203,204,205,206])
b

201    a
202    b
203    a
204    a
205    s
206    g
dtype: object

In [16]:
b.head(4)

201    a
202    b
203    a
204    a
dtype: object

In [17]:
b.tail(3)

204    a
205    s
206    g
dtype: object

In [18]:
b.info();b#basic info about series

<class 'pandas.core.series.Series'>
Index: 6 entries, 201 to 206
Series name: None
Non-Null Count  Dtype
--------------  -----
6 non-null      object
dtypes: object(1)
memory usage: 96.0+ bytes

201    a
202    b
203    a
204    a
205    s
206    g
dtype: object

In [19]:
b.describe()#statical info about series
# object=count,unique,top,freq
# int=count,min,max,mean,std,25,50,75

count     6
unique    4
top       a
freq      3
dtype: object

In [20]:
g=pd.Series([1,2,3,9,4])
g

0    1
1    2
2    3
3    9
4    4
dtype: int64

In [21]:
g.astype(float)

0    1.0
1    2.0
2    3.0
3    9.0
4    4.0
dtype: float64

In [22]:
g.astype(object)

0    1
1    2
2    3
3    9
4    4
dtype: object

In [23]:
marks = [90,76,87,98,98,98,65,65,54,69]
df=pd.DataFrame(marks)
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [24]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       10 non-null     int64
dtypes: int64(1)
memory usage: 212.0 bytes
None

In [25]:
print(df.describe())

               0
count  10.000000
mean   80.000000
std    16.275407
min    54.000000
25%    66.000000
50%    81.500000
75%    96.000000
max    98.000000

In [26]:
students=[["abhi",90],["bala",80],["charles",77],["david",66],["elaine",55]]
df1=pd.DataFrame(students,columns=["name","english"])
df1

      name  english
0     abhi       90
1     bala       80
2  charles       77
3    david       66
4   elaine       55

In [27]:
df1["maths"]=pd.Series([99,68,65,89,87])
df1

      name  english  maths
0     abhi       90     99
1     bala       80     68
2  charles       77     65
3    david       66     89
4   elaine       55     87

In [28]:
df1["total"]=df1["english"]+df1["maths"]
df1

      name  english  maths  total
0     abhi       90     99    189
1     bala       80     68    148
2  charles       77     65    142
3    david       66     89    155
4   elaine       55     87    142

In [29]:
print(df1["maths"])#access the single column

0    99
1    68
2    65
3    89
4    87
Name: maths, dtype: int64

In [30]:
print(df1[["maths","name"]])#access the double column by[[]]

   maths     name
0     99     abhi
1     68     bala
2     65  charles
3     89    david
4     87   elaine

In [31]:
df1.columns

Index(['name', 'english', 'maths', 'total'], dtype='object')

In [32]:
del df1["total"]
df1

      name  english  maths
0     abhi       90     99
1     bala       80     68
2  charles       77     65
3    david       66     89
4   elaine       55     87

In [33]:
df1["average"]=(df1["english"]+df1["maths"])/2
df1

      name  english  maths  average
0     abhi       90     99     94.5
1     bala       80     68     74.0
2  charles       77     65     71.0
3    david       66     89     77.5
4   elaine       55     87     71.0

In [34]:
import seaborn as sns
df2=sns.load_dataset("mpg")
df2

HTTPError: HTTP Error 429: Too Many Requests

In [ ]:
df2.head(10)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
5,15.0,8,429.0,198.0,4341,10.0,70,usa,ford galaxie 500
6,14.0,8,454.0,220.0,4354,9.0,70,usa,chevrolet impala
7,14.0,8,440.0,215.0,4312,8.5,70,usa,plymouth fury iii
8,14.0,8,455.0,225.0,4425,10.0,70,usa,pontiac catalina
9,15.0,8,390.0,190.0,3850,8.5,70,usa,amc ambassador dpl

In [ ]:
df2.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [ ]:
df2.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [ ]:
df2.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

In [ ]:
df2.describe(include="all") #gives object and int both

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,usa,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,249,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,NaN,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,NaN,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,NaN,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,NaN,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,NaN,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,NaN,NaN
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,NaN,NaN

In [ ]:
df2.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [ ]:
df2[['acceleration','model_year','displacement']]

     acceleration  model_year  displacement
0            12.0          70         307.0
1            11.5          70         350.0
2            11.0          70         318.0
3            12.0          70         304.0
4            10.5          70         302.0
..            ...         ...           ...
393          15.6          82         140.0
394          24.6          82          97.0
395          11.6          82         135.0
396          18.6          82         120.0
397          19.4          82         119.0

[398 rows x 3 columns]

In [ ]:
df2.iloc[1]

mpg                          15.0
cylinders                       8
displacement                350.0
horsepower                  165.0
weight                       3693
acceleration                 11.5
model_year                     70
origin                        usa
name            buick skylark 320
Name: 1, dtype: object

In [ ]:
df2.iloc[2:5]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [ ]:
df2.iloc[2:5,0:3]

    mpg  cylinders  displacement
2  18.0          8         318.0
3  16.0          8         304.0
4  17.0          8         302.0

In [ ]:
df2.loc[5:11,'horsepower':]

    horsepower  weight  acceleration  model_year origin                 name
5        198.0    4341          10.0          70    usa     ford galaxie 500
6        220.0    4354           9.0          70    usa     chevrolet impala
7        215.0    4312           8.5          70    usa    plymouth fury iii
8        225.0    4425          10.0          70    usa     pontiac catalina
9        190.0    3850           8.5          70    usa   amc ambassador dpl
10       170.0    3563          10.0          70    usa  dodge challenger se
11       160.0    3609           8.0          70    usa   plymouth 'cuda 340

In [ ]:
df2.loc[:5,["mpg","name","origin","weight"]]

    mpg                       name origin  weight
0  18.0  chevrolet chevelle malibu    usa    3504
1  15.0          buick skylark 320    usa    3693
2  18.0         plymouth satellite    usa    3436
3  16.0              amc rebel sst    usa    3433
4  17.0                ford torino    usa    3449
5  15.0           ford galaxie 500    usa    4341

In [ ]:
df2.loc[:5,["mpg","name","origin","weight"]]

    mpg                       name origin  weight
0  18.0  chevrolet chevelle malibu    usa    3504
1  15.0          buick skylark 320    usa    3693
2  18.0         plymouth satellite    usa    3436
3  16.0              amc rebel sst    usa    3433
4  17.0                ford torino    usa    3449
5  15.0           ford galaxie 500    usa    4341

In [ ]:
df2.loc[10:51]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
10,15.0,8,383.0,170.0,3563,10.0,70,usa,dodge challenger se
11,14.0,8,340.0,160.0,3609,8.0,70,usa,plymouth 'cuda 340
12,15.0,8,400.0,150.0,3761,9.5,70,usa,chevrolet monte carlo
13,14.0,8,455.0,225.0,3086,10.0,70,usa,buick estate wagon (sw)
14,24.0,4,113.0,95.0,2372,15.0,70,japan,toyota corona mark ii
15,22.0,6,198.0,95.0,2833,15.5,70,usa,plymouth duster
16,18.0,6,199.0,97.0,2774,15.5,70,usa,amc hornet
17,21.0,6,200.0,85.0,2587,16.0,70,usa,ford maverick
18,27.0,4,97.0,88.0,2130,14.5,70,japan,datsun pl510
19,26.0,4,97.0,46.0,1835,20.5,70,europe,volkswagen 1131 deluxe sedan
20,25.0,4,110.0,87.0,2672,17.5,70,europe,peugeot 504
21,24.0,4,107.0,90.0,2430,14.5,70,europe,audi 100 ls
22,25.0,4,104.0,95.0,2375,17.5,70,europe,saab 99e
23,26.0,4,121.0,113.0,2234,12.5,70,europe,bmw 2002
24,21.0,6,199.0,90.0,2648,15.0,70,usa,amc gremlin
25,10.0,8,360.0,215.0,4615,14.0,70,usa,ford f250
26,10.0,8,307.0,200.0,4376,15.0,70,usa,chevy c20
27,11.0,8,318.0,210.0,4382,13.5,70,usa,dodge d200
28,9.0,8,304.0,193.0,4732,18.5,70,usa,hi 1200d
29,27.0,4,97.0,88.0,2130,14.5,71,japan,datsun pl510
30,28.0,4,140.0,90.0,2264,15.5,71,usa,chevrolet vega 2300
31,25.0,4,113.0,95.0,2228,14.0,71,japan,toyota corona
32,25.0,4,98.0,NaN,2046,19.0,71,usa,ford pinto
33,19.0,6,232.0,100.0,2634,13.0,71,usa,amc gremlin
34,16.0,6,225.0,105.0,3439,15.5,71,usa,plymouth satellite custom
35,17.0,6,250.0,100.0,3329,15.5,71,usa,chevrolet chevelle malibu
36,19.0,6,250.0,88.0,3302,15.5,71,usa,ford torino 500
37,18.0,6,232.0,100.0,3288,15.5,71,usa,amc matador
38,14.0,8,350.0,165.0,4209,12.0,71,usa,chevrolet impala
39,14.0,8,400.0,175.0,4464,11.5,71,usa,pontiac catalina brougham
40,14.0,8,351.0,153.0,4154,13.5,71,usa,ford galaxie 500
41,14.0,8,318.0,150.0,4096,13.0,71,usa,plymouth fury iii
42,12.0,8,383.0,180.0,4955,11.5,71,usa,dodge monaco (sw)
43,13.0,8,400.0,170.0,4746,12.0,71,usa,ford country squire (sw)
44,13.0,8,400.0,175.0,5140,12.0,71,usa,pontiac safari (sw)
45,18.0,6,258.0,110.0,2962,13.5,71,usa,amc hornet sportabout (sw)
46,22.0,4,140.0,72.0,2408,19.0,71,usa,chevrolet vega (sw)
47,19.0,6,250.0,100.0,3282,15.0,71,usa,pontiac firebird
48,18.0,6,250.0,88.0,3139,14.5,71,usa,ford mustang
49,23.0,4,122.0,86.0,2220,14.0,71,usa,mercury capri 2000
50,28.0,4,116.0,90.0,2123,14.0,71,europe,opel 1900
51,30.0,4,79.0,70.0,2074,19.5,71,europe,peugeot 304

In [ ]:
g=df2.loc[(df2.model_year>70,["cylinders"])]=20
print(g)

20

In [ ]:
df2.loc[(df2.model_year>70),["cylinders"]]

     cylinders
29          20
30          20
31          20
32          20
33          20
..         ...
393         20
394         20
395         20
396         20
397         20

[369 rows x 1 columns]

In [ ]:
df2.loc[(df2.model_year>70),["cylinders","model_year"]]

     cylinders  model_year
29          20          71
30          20          71
31          20          71
32          20          71
33          20          71
..         ...         ...
393         20          82
394         20          82
395         20          82
396         20          82
397         20          82

[369 rows x 2 columns]

In [ ]:
df2["cylinders"].value_counts()

cylinders
20    369
8      18
4       7
6       4
Name: count, dtype: int64

In [ ]:
df2.loc[(df2.origin=="europe")&(df2.model_year>70)]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
50,28.0,20,116.0,90.0,2123,14.0,71,europe,opel 1900
51,30.0,20,79.0,70.0,2074,19.5,71,europe,peugeot 304
52,30.0,20,88.0,76.0,2065,14.5,71,europe,fiat 124b
55,27.0,20,97.0,60.0,1834,19.0,71,europe,volkswagen model 111
59,23.0,20,97.0,54.0,2254,23.5,72,europe,volkswagen type 3
...,...,...,...,...,...,...,...,...,...
354,34.5,20,100.0,NaN,2320,15.8,81,europe,renault 18i
359,28.1,20,141.0,80.0,3230,20.4,81,europe,peugeot 505s turbo diesel
360,30.7,20,145.0,76.0,3160,19.6,81,europe,volvo diesel
375,36.0,20,105.0,74.0,1980,15.3,82,europe,volkswagen rabbit l
394,44.0,20,97.0,52.0,2130,24.6,82,europe,vw pickup

In [ ]:
df2["origin"].unique()

array(['usa', 'japan', 'europe'], dtype=object)

In [ ]:
df2[df2["origin"]=="japan"]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
14,24.0,4,113.0,95.0,2372,15.0,70,japan,toyota corona mark ii
18,27.0,4,97.0,88.0,2130,14.5,70,japan,datsun pl510
29,27.0,20,97.0,88.0,2130,14.5,71,japan,datsun pl510
31,25.0,20,113.0,95.0,2228,14.0,71,japan,toyota corona
53,31.0,20,71.0,65.0,1773,19.0,71,japan,toyota corolla 1200
...,...,...,...,...,...,...,...,...,...
382,34.0,20,108.0,70.0,2245,16.9,82,japan,toyota corolla
383,38.0,20,91.0,67.0,1965,15.0,82,japan,honda civic
384,32.0,20,91.0,67.0,1965,15.7,82,japan,honda civic (auto)
385,38.0,20,91.0,67.0,1995,16.2,82,japan,datsun 310 gx
390,32.0,20,144.0,96.0,2665,13.9,82,japan,toyota celica gt

In [ ]:
df2["origin"].value_counts()

origin
usa       249
japan      79
europe     70
Name: count, dtype: int64

In [ ]:
df2.drop("displacement",axis=1)#column wise dropping

,mpg,cylinders,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...
393,27.0,20,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,20,52.0,2130,24.6,82,europe,vw pickup
395,32.0,20,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,20,79.0,2625,18.6,82,usa,ford ranger
397,31.0,20,82.0,2720,19.4,82,usa,chevy s-10

In [ ]:
df2.drop(4) #drop based on rows

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
5,15.0,8,429.0,198.0,4341,10.0,70,usa,ford galaxie 500
...,...,...,...,...,...,...,...,...,...
393,27.0,20,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,20,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,20,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,20,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,20,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [ ]:
# DAY -3 
import numpy as np 
import pandas as pd

In [ ]:
data={
    'Category':['A','B','A','B','A','B','A','B'],
    'Store':['S1','S1','S2','S2','S1','S2','S2','S1'],
    'Sales':[100,200,150,250,120,100,200,300],
    'Quantity':[10,15,12,18,8,20,15,25],
    'Date':pd.date_range('2023-01-01',periods=8)
}
df=pd.DataFrame(data)
df

In [ ]:
cat_sales_sum=df.groupby('Category')['Sales'].sum()
cat_sales_sum

Category
A    570
B    850
Name: Sales, dtype: int64

In [ ]:
sto_sales_sum=df.groupby('Store')['Sales'].sum()
sto_sales_sum

Store
S1    720
S2    700
Name: Sales, dtype: int64

In [ ]:
multi_sales_sum=df.groupby(['Category','Store'])['Sales'].sum()
multi_sales_sum

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       350
Name: Sales, dtype: int64

In [ ]:
# convert the multiindex series to a clean dataframe
multi_sales_df=multi_sales_sum.reset_index()
multi_sales_df

  Category Store  Sales
0        A    S1    220
1        A    S2    350
2        B    S1    500
3        B    S2    350

In [ ]:
# calculate multiple descriptive statistics for the sales column
df['Sales'].agg(['mean','median','min','max','std','count','var'])

mean       177.500000
median     175.000000
min        100.000000
max        300.000000
std         73.045974
count        8.000000
var       5335.714286
Name: Sales, dtype: float64

In [ ]:
grouped_agg=df.groupby('Category').agg({
    'Sales':['sum','max'],
    'Quantity':['mean','median']
})
grouped_agg

         Sales      Quantity
           sum  max     mean median
Category
A          570  200    11.25   11.0
B          850  300    19.50   19.0

In [ ]:
employees=pd.DataFrame({
    'employee_id':[1,2,3,4,5],
    'name':['John','Amaa','Peter','Linda','Bob'],
    'department':['HR','IT','Finance','IT','HR']
})
salaries=pd.DataFrame({
    'employee_id':[1,2,3,6,7],
    'salary':[20000,45000,38000,28000,30000],
    'bonus':[5000,2000,3000,3500,2500]
})
print("---Employee Data---\n",employees)
print("---salary data---\n",salaries)

---Employee Data---
    employee_id   name department
0            1   John         HR
1            2   Amaa         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR
---salary data---
    employee_id  salary  bonus
0            1   20000   5000
1            2   45000   2000
2            3   38000   3000
3            6   28000   3500
4            7   30000   2500

In [ ]:
pd.merge(employees,salaries,on='employee_id',how='inner') #inner merge: gives the commom data values from both the dataframes

   employee_id   name department  salary  bonus
0            1   John         HR   20000   5000
1            2   Amaa         IT   45000   2000
2            3  Peter    Finance   38000   3000

In [ ]:
pd.merge(employees,salaries,on='employee_id',how='outer') #outer merge :gives all the rows from both the data frames

   employee_id   name department   salary   bonus
0            1   John         HR  20000.0  5000.0
1            2   Amaa         IT  45000.0  2000.0
2            3  Peter    Finance  38000.0  3000.0
3            4  Linda         IT      NaN     NaN
4            5    Bob         HR      NaN     NaN
5            6    NaN        NaN  28000.0  3500.0
6            7    NaN        NaN  30000.0  2500.0

In [ ]:
pd.merge(employees,salaries,on='employee_id',how='left')
#left_merge : include all rows from the left dataframes and only matching rows from right dataframes

   employee_id   name department   salary   bonus
0            1   John         HR  20000.0  5000.0
1            2   Amaa         IT  45000.0  2000.0
2            3  Peter    Finance  38000.0  3000.0
3            4  Linda         IT      NaN     NaN
4            5    Bob         HR      NaN     NaN

In [ ]:
pd.merge(employees,salaries,on='employee_id',how='right')
#right_merge : include all rows from the right dataframes and only matching rows from left dataframes

   employee_id   name department  salary  bonus
0            1   John         HR   20000   5000
1            2   Amaa         IT   45000   2000
2            3  Peter    Finance   38000   3000
3            6    NaN        NaN   28000   3500
4            7    NaN        NaN   30000   2500

In [ ]:
df1=pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2']
    })
df2=pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5']
})

NameError: name 'pd' is not defined

In [ ]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1,df2],axis=1) #horizontal concatenation

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [ ]:
df_a=pd.DataFrame({
    'Name':['Alice','Bob','Charlie']
},index=[1,2,3])
df_b=pd.DataFrame({
    'score':[80,75,90]
},index=[2,3,4])

In [ ]:
df_a.join(df_b)

      Name  score
1    Alice    NaN
2      Bob   80.0
3  Charlie   75.0

In [ ]:
df_a.join(df_b,how='outer')

      Name  score
1    Alice    NaN
2      Bob   80.0
3  Charlie   75.0
4      NaN   90.0

In [ ]:
df5 = pd.DataFrame({
    "Date": [
        "2024-01-01", "2024-01-02", "2024-01-03", "2024-01-04",
        "2024-01-05", "2024-01-06", "2024-01-07", "2024-01-08",
        "2024-01-09", "2024-01-10"
    ],
    "Product": [
        "Laptop", "Phone", "Tablet", "Monitor", "Keyboard",
        "Mouse", "Laptop", "Phone", "Tablet", "Monitor"
    ],
    "Region": [
        "North", "South", "East", "West", "North",
        "South", "East", "West", "North", "South"
    ],
    "Sales": [
        1200, 800, 600, 450, 150,
        100, 1800, 950, 700, 550
    ],
    "Units": [
        2, 4, 3, 5, 10,
        12, 3, 5, 4, 6
    ],
    "Rep": [
        "Alice", "Bob", "Charlie", "Diana", "Ethan",
        "Alice", "Bob", "Charlie", "Diana", "Ethan"
    ]
})

df5["Date"] = pd.to_datetime(df5["Date"])

print(df)