In [1]:
pip install pdfplumber

Requirement already satisfied: pdfplumber in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (0.11.10)
Requirement already satisfied: pdfminer.six==20260107 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pdfplumber) (20260107)
Requirement already satisfied: Pillow>=12.2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pdfplumber) (12.3.0)
Requirement already satisfied: pypdfium2>=5.9.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pdfplumber) (5.11.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pdfminer.six==20260107->pdfplumber) (3.4.2)
Requirement already satisfied: cryptography>=36.0.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pdfminer.six==20260107->pdfplumber) (49.0.0)
Requirement already satisfied: cffi>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (3.0)

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import pdfplumber

In [4]:
with pdfplumber.open("pokemon_data.pdf") as pdf:
    table = pdf.pages[0].extract_table()

In [5]:
df = pd.DataFrame(table[1:],columns=table[0])
df.to_csv("pokemon.csv",index = False)

In [6]:
df.head()

   #            Name        Type 1  Type 2  HP Attack
0  1       Bulbasaur         Grass  Poison  45     49
1  2         Ivysaur         Grass  Poison  60     62
2  3        Venusaur         Grass  Poison  80     82
3  3  VenusaurMega V  eGnruassasur  Poison  80    100
4  4      Charmander          Fire          39     52

In [8]:
df.tail(11)

     #             Name   Type 1  Type 2   HP Attack
34  29  Nidoran (Female  )Poison           55     47
35  30         Nidorina   Poison           70     62
36  31        Nidoqueen   Poison  Ground   90     92
37  32   Nidoran (Male)   Poison           46     57
38  33         Nidorino   Poison           61     72
39  34         Nidoking   Poison  Ground   81    102
40  35         Clefairy    Fairy           70     45
41  36         Clefable    Fairy           95     70
42  37           Vulpix     Fire           38     41
43  38        Ninetales     Fire           73     76
44  39       Jigglypuff   Normal   Fairy  115     45

In [9]:
df.shape

(45, 6)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   #       45 non-null     object
 1   Name    45 non-null     object
 2   Type 1  45 non-null     object
 3   Type 2  45 non-null     object
 4   HP      45 non-null     object
 5   Attack  45 non-null     object
dtypes: object(6)
memory usage: 2.2+ KB

In [11]:
df.isnull().sum()

#         0
Name      0
Type 1    0
Type 2    0
HP        0
Attack    0
dtype: int64

In [12]:
df.describe()

         #             Name  Type 1 Type 2  HP Attack
count   45               45      45     45  45     45
unique  39               44      16      6  27     35
top      6  CharizardMega C  Normal         60     45
freq     3                2       8     24   4      4

In [14]:
df.drop_duplicates()

     #             Name          Type 1  Type 2   HP Attack
0    1        Bulbasaur           Grass  Poison   45     49
1    2          Ivysaur           Grass  Poison   60     62
2    3         Venusaur           Grass  Poison   80     82
3    3   VenusaurMega V    eGnruassasur  Poison   80    100
4    4       Charmander            Fire           39     52
5    5       Charmeleon            Fire           58     64
6    6        Charizard            Fire  Flying   78     84
7    6  CharizardMega C  Fhiarerizard X  Dragon   78    130
8    6  CharizardMega C  Fhiarerizard Y  Flying   78    104
9    7         Squirtle           Water           44     48
10   8        Wartortle           Water           59     63
11   9        Blastoise           Water           79     83
12   9  BlastoiseMega B   laWsatoteisre           79    103
13  10         Caterpie             Bug           45     30
14  11          Metapod             Bug           50     20
15  12       Butterfree             Bug  Flying   60     45
16  13           Weedle             Bug  Poison   40     35
17  14           Kakuna             Bug  Poison   45     25
18  15         Beedrill             Bug  Poison   65     90
19  15  BeedrillMega Be       eBdurigll  Poison   65    150
20  16           Pidgey          Normal  Flying   40     45
21  17        Pidgeotto          Normal  Flying   63     60
22  18          Pidgeot          Normal  Flying   83     80
23  18  PidgeotMega Pid      gNeoortmal  Flying   83     80
24  19          Rattata          Normal           30     56
25  20         Raticate          Normal           55     81
26  21          Spearow          Normal  Flying   40     60
27  22           Fearow          Normal  Flying   65     90
28  23            Ekans          Poison           35     60
29  24            Arbok          Poison           60     85
30  25          Pikachu        Electric           35     55
31  26           Raichu        Electric           60     90
32  27        Sandshrew          Ground           50     75
33  28        Sandslash          Ground           75    100
34  29  Nidoran (Female         )Poison           55     47
35  30         Nidorina          Poison           70     62
36  31        Nidoqueen          Poison  Ground   90     92
37  32   Nidoran (Male)          Poison           46     57
38  33         Nidorino          Poison           61     72
39  34         Nidoking          Poison  Ground   81    102
40  35         Clefairy           Fairy           70     45
41  36         Clefable           Fairy           95     70
42  37           Vulpix            Fire           38     41
43  38        Ninetales            Fire           73     76
44  39       Jigglypuff          Normal   Fairy  115     45

In [15]:
df.shape

(45, 6)

In [16]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.max()

#                     9
Name             Weedle
Type 1    laWsatoteisre
Type 2           Poison
HP                   95
Attack               92
dtype: object

In [21]:
df.min()

#               1
Name        Arbok
Type 1    )Poison
Type 2
HP            115
Attack        100
dtype: object

In [22]:
df.sample()

     #      Name Type 1 Type 2  HP Attack
13  10  Caterpie    Bug         45     30

In [21]:
df2 = pd.read_csv("airbnb - airbnb.csv")
print(df2.head(5))
print("new csv")

   Unnamed: 0  listing_id                                               name  \
0           0    13740704  Cozy,budget friendly, cable inc, private entra...
1           1    22005115              Two floor apartment near Central Park
2           2    21667615                  Beautiful 1BR in Brooklyn Heights
3           3     6425850                          Spacious, charming studio
4           4    22986519              Bedroom on the lively Lower East Side

     host_id host_name          neighbourhood_full            coordinates  \
0   20583125    Michel         Brooklyn, Flatlands  (40.63222, -73.93398)
1   82746113   Cecilia  Manhattan, Upper West Side  (40.78761, -73.96862)
2      78251    Leslie  Brooklyn, Brooklyn Heights   (40.7007, -73.99517)
3   32715865    Yelena  Manhattan, Upper West Side  (40.79169, -73.97498)
4  154262349    Brooke  Manhattan, Lower East Side  (40.71884, -73.98354)

         room_type price  number_of_reviews last_review  reviews_per_month  \
0     Private room   45$                 10  2018-12-12               0.70
1  Entire home/apt  135$                  1  2019-06-30               1.00
2  Entire home/apt  150$                  0         NaN                NaN
3  Entire home/apt   86$                  5  2017-09-23               0.13
4     Private room  160$                 23  2019-06-12               2.29

   availability_365    rating  number_of_stays   5_stars listing_added
0                85  4.100954             12.0  0.609432    2018-06-08
1               145  3.367600              1.2  0.746135    2018-12-25
2                65       NaN              NaN       NaN    2018-08-15
3                 0  4.763203              6.0  0.769947    2017-03-20
4               102  3.822591             27.6  0.649383    2020-10-23
new csv

In [20]:
df3 = pd.read_csv("sales_data_sample - sales_data_sample.csv")
print(df3.head(5))

   ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0        10107               30      95.70                2  2871.00
1        10121               34      81.35                5  2765.90
2        10134               41      94.74                2  3884.34
3        10145               45      83.26                6  3746.70
4        10159               49     100.00               14  5205.27

         ORDERDATE   STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
0   2/24/2003 0:00  Shipped       1         2     2003  ...
1    5/7/2003 0:00  Shipped       2         5     2003  ...
2    7/1/2003 0:00  Shipped       3         7     2003  ...
3   8/25/2003 0:00  Shipped       3         8     2003  ...
4  10/10/2003 0:00  Shipped       4        10     2003  ...

                    ADDRESSLINE1  ADDRESSLINE2           CITY STATE  \
0        897 Long Airport Avenue           NaN            NYC    NY
1             59 rue de l'Abbaye           NaN          Reims   NaN
2  27 rue du Colonel Pierre Avia           NaN          Paris   NaN
3             78934 Hillside Dr.           NaN       Pasadena    CA
4                7734 Strong St.           NaN  San Francisco    CA

  POSTALCODE COUNTRY TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE
0      10022     USA       NaN              Yu             Kwai    Small
1      51100  France      EMEA         Henriot             Paul    Small
2      75508  France      EMEA        Da Cunha           Daniel   Medium
3      90003     USA       NaN           Young            Julie   Medium
4        NaN     USA       NaN           Brown            Julie   Medium

[5 rows x 25 columns]